-- AUTOSTART
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
--     hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Sweet-Ambar-Blue-Dark-v40'")
--     hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
--     hl.exec_cmd("gsettings set org.gnome.desktop.interface font-name 'Ubuntu 11'")
--     hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme 'kora'")
    hl.exec_cmd("swaync")
    hl.exec_cmd("wl-paste --watch cliphist store &")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("gnome-keyring-daemon --start")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &")
end)
