# WAYBAR
layerrule {
    name = layerrule-1
    blur = on
    blur_popups = on
    ignore_alpha = 0
    # ignore_alpha = 0.5
    match:namespace = waybar
}

# WLOGOUT
layerrule {
    name = layerrule-2
    blur = on
    match:namespace = logout_dialog
}

# ROFI
layerrule {
    name = layerrule-3
    blur = on
    ignore_alpha = 0
    # dim_around = on
    animation = popin 75%
    match:namespace = rofi
}

# SwayNC notifications panel
layerrule {
    name = layerrule-4
    animation = slide right
    blur = on
    ignore_alpha = 0
    match:namespace = swaync-control-center
}

layerrule {
    name = layerrule-5
    blur = on
    ignore_alpha = 0
    match:namespace = swaync-notification-window
}
