-- Generated by matugen
return {
    image = "{{image}}",
    <* for name, value in colors *>
    {{name}} = "0xff{{value.default.hex_stripped}}",
    <* endfor *>
}
-- return {
--     primary   = "rgba({{colors.primary.default.hex_stripped}}ee)",
--     secondary = "rgba({{colors.secondary.default.hex_stripped}}ee)",
--     surface   = "rgba({{colors.surface_container.default.hex_stripped}}aa)",
--     outline   = "rgba({{colors.outline.default.hex_stripped}}aa)",
-- }
