#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = waybar
exec-once = awww-daemon
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Sweet-Ambar-Blue-Dark-v40"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gnome.desktop.interface font-name "Ubuntu 11"
exec-once = swaync
exec-once = gsettings set org.gnome.desktop.interface icon-theme "kora"

# Clipboard
exec-once = wl-paste --watch cliphist store &


###############
exec-once = dbus-update-activation-environment --all
exec-once = gnome-keyring-daemon --start
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# exec-once = systemctl --user start hyprpolkitagent
