# --- Main Colors ---
background            #0e1415
foreground            #dde4e3
cursor                #dde4e3
cursor_text_color     #0e1415

selection_background  #324b4c
selection_foreground  #cce8e8

url_color             #b5c7e9

# --- ANSI Colors ---
color0                #0e1415
color1                #ffb4ab
color2                #b5c7e9
color3                #b0cccc
color4                #80d4d7
color5                #b5c7e9
color6                #b0cccc
color7                #dde4e3

color8                #3f4949
color9                #93000a
color10               #354763
color11               #324b4c
color12               #004f52
color13               #324b4c
color14               #354763
color15               #bec8c8

# --- Starship Prompt Bubbles ---
color255              #004f52
color254              #80d4d7
color253              #324b4c
color252              #b0cccc
color251              #354763
color250              #b5c7e9
color249              #93000a
color248              #ffb4ab

color232              #9cf1f4
color233              #003738
color234              #cce8e8
color235              #1b3435
color236              #d5e3ff
color237              #1e314c
color238              #ffdad6
color239              #690005
color240              #9cf1f4

# Matched with unthemed light/dark
color243              #80d4d7
color244              #ffb4ab
color245              #3f4949

# --- UI Elements ---
active_tab_foreground   #003738
active_tab_background   #80d4d7
inactive_tab_foreground #9cf1f4
inactive_tab_background #004f52

active_border_color     #80d4d7
inactive_border_color   #899393

# --- Marks ---
mark1_foreground        #002021
mark1_background        #9cf1f4
mark2_foreground        #041f20
mark2_background        #cce8e8
mark3_foreground        #071c36
mark3_background        #d5e3ff
